sonar.projectKey=valkdev_bomberman-multiplayer
sonar.organization=valkdev
sonar.exclusions=assets/**,Core/**,Entities/**,Managers/**,Scenes/**,Util/**,**/third_party/**

# Ignore coverage for all files
sonar.coverage.exclusions=**/*
