; Default logging configuration for the game.
; The observed log level per channel is the strictest between the global log level and the channel log level.
; The log levels are: trace, debug, info, warn, error
[log]
level=info

[channels]
client=info
server=info
game=info
net.conn=info
net.packet=warn
net.proto=info
net.input=debug
net.snapshot=debug
net.diag=info